### ISSUE TITLE
Please choose a license!

### ISSUE THREAD

**Issue by qdw** [ideamonk/Rambola#3]
Please choose a licence — any open-source licence will do — so that we can run, share and modify this excellent package!

Background: I want to make some changes to this code, but it has no licence, which means it defaults to "copyrighted; all rights reserved." I cannot legally modify it. In fact, it appears I can't even run it: I can only view it on GitHub. http://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github

Best regards,
Quinn

**Comment by ideamonk** [comment]
Hey Quinn,

Added a BSD style license. Thanks for pointing out.

Best,

Please note that I no longer use or maintain these scripts.

**Comment by qdw** [comment]
Super, thanks so much! I'm going to fork these scripts and adapt them somewhat. I see a number of other users have forked them too, so maybe I'll see which forks are active. I really appreciate the info and the prompt response.

Best,
Quinn
